version: '3.9'


services:
  main:
    build:
      context: .
      dockerfile: Dockerfile
    image: kagemeka/dsalgo-go:latest
    restart: on-failure
    tty: true
    volumes:
      - type: bind
        source: $ROOT
        target: /root/$PROJECT
        volume: 
          nocopy: true
    working_dir: /root/$PROJECT
  
